name: Unity Credentials Test

on:
  workflow_dispatch: {}

jobs:
  test-credentials:
    name: Validate Unity Credentials
    runs-on: ubuntu-latest

    env:
      UNITY_EMAIL:    ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_LICENSE:  ${{ secrets.UNITY_LICENSE }}        
      UNITY_VERSION:  6000.0.60f1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Try Unity Activation
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
          targetPlatform: StandaloneLinux64
          projectPath: .
          buildName: DummyBuild
          buildPath: dummy-output
